# .github/workflow/nodejs.yml
name: Node.js CI

on:
  push

jobs:
  build:
    steps:
    - run: npm ci
    - run: npm run build --if-present
    - run: npx relative-ci-agent
      env:
        RELATIVE_CI_KEY: ${{ secrets.RELATIVE_CI_KEY }}